package org.BsXinQin.kinswathe.roles.dreamer;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.PlayerPoisonComponent;
import dev.doctor4t.wathe.cca.PlayerShopComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.Identifier;
import org.BsXinQin.kinswathe.KinsWathe;
import org.BsXinQin.kinswathe.KinsWatheRoles;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import org.jetbrains.annotations.NotNull;
import org.ladysnake.cca.api.v3.component.ComponentKey;
import org.ladysnake.cca.api.v3.component.ComponentRegistry;
import org.ladysnake.cca.api.v3.component.sync.AutoSyncedComponent;
import org.ladysnake.cca.api.v3.component.tick.ServerTickingComponent;

import java.util.ArrayList;
import java.util.Collections;

public class DreamerKillerComponent implements AutoSyncedComponent, ServerTickingComponent {

    public static final ComponentKey<DreamerKillerComponent> KEY = ComponentRegistry.getOrCreate(Identifier.of(KinsWathe.MOD_ID, "dreamer_killer"), DreamerKillerComponent.class);

    @NotNull private final PlayerEntity player;
    public boolean hasBecomeKiller = false;
    public int dreamerRequired = 0;
    public int dreamerCounts = 0;

    public DreamerKillerComponent(@NotNull PlayerEntity player) {this.player = player;}

    @Override
    public void serverTick() {
        this.setDreamerRequired();
        if (!this.hasBecomeKiller && this.dreamerCounts > 0) {
            this.notInGameReset();
            if (this.dreamerCounts == this.dreamerRequired) {
                this.triggerBecomeKiller();
                this.reset();
            }
        }
    }

    public void notInGameReset() {
        if (GameWorldComponent.KEY.get(this.player.getWorld()).getRole(this.player) == null) {
            this.reset();
        }
    }

    public void setDreamerRequired() {
        if (!GameWorldComponent.KEY.get(this.player.getWorld()).isRunning() && this.dreamerRequired != this.player.getServer().getPlayerManager().getCurrentPlayerCount() / 4) {
            this.dreamerRequired = this.player.getServer().getPlayerManager().getCurrentPlayerCount() / 4;
            this.sync();
        }
    }

    public void triggerBecomeKiller() {
        GameWorldComponent gameWorld = GameWorldComponent.KEY.get(this.player.getWorld());
        if (!gameWorld.isRole(this.player, KinsWatheRoles.DREAMER) && GameFunctions.isPlayerSpectatingOrCreative(this.player)) return;
        ArrayList<Role> shuffledKillerRoles = new ArrayList<>(WatheRoles.ROLES);
        shuffledKillerRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !role.canUseKiller() || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath()));
        if (shuffledKillerRoles.isEmpty()) shuffledKillerRoles.add(WatheRoles.KILLER);
        Collections.shuffle(shuffledKillerRoles);
        PlayerShopComponent playerShop = PlayerShopComponent.KEY.get(this.player);
        gameWorld.addRole(this.player, shuffledKillerRoles.getFirst());
        ModdedRoleAssigned.EVENT.invoker().assignModdedRole(this.player, shuffledKillerRoles.getFirst());
        playerShop.balance += 100;
        playerShop.sync();
        PlayerPoisonComponent.KEY.get(this.player).reset();
        if (Harpymodloader.VANNILA_ROLES.contains(gameWorld.getRole(this.player))) {
            ServerPlayNetworking.send((ServerPlayerEntity) this.player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(WatheRoles.KILLER), gameWorld.getAllKillerTeamPlayers().size(), 0));
        } else {
            ServerPlayNetworking.send((ServerPlayerEntity) this.player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(gameWorld.getRole(this.player))), gameWorld.getAllKillerTeamPlayers().size(), 0));
        }
        this.hasBecomeKiller = true;
        this.sync();
    }

    public void reset() {
        this.hasBecomeKiller = false;
        this.dreamerCounts = 0;
        this.sync();
    }

    public void sync() {
        KEY.sync(this.player);
    }

    @Override
    public void writeToNbt(@NotNull NbtCompound tag, RegistryWrapper.@NotNull WrapperLookup registryLookup) {
        tag.putInt("dreamerCounts", this.dreamerCounts);
        tag.putInt("dreamerRequired", this.dreamerRequired);
        tag.putBoolean("hasBecomeKiller", this.hasBecomeKiller);
    }

    @Override
    public void readFromNbt(@NotNull NbtCompound tag, RegistryWrapper.@NotNull WrapperLookup registryLookup) {
        this.dreamerCounts = tag.contains("dreamerCounts") ? tag.getInt("dreamerCounts") : 0;
        this.dreamerRequired = tag.contains("dreamerRequired") ? tag.getInt("dreamerRequired") : 0;
        this.hasBecomeKiller = tag.contains("hasBecomeKiller") && tag.getBoolean("hasBecomeKiller");
    }
}